name: Metrics
on:
  # Schedule updates (Every 6 hours)
  schedule: [{ cron: "0 */6 * * *" }]
  # Allow manual triggering
  workflow_dispatch:
  # Run on every push (no branch filter)
  push: { branches: [] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
      issues: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create "dist" branch if it doesn't exist
        run: |
          git fetch origin
          if ! git ls-remote --exit-code origin dist; then
            git checkout --orphan dist
            git config user.email "github-actions@github.com"
            git config user.name "GitHub Actions"
            git rm -rf .
            mkdir -p metrics
            echo "Initial commit for dist branch" > README.md
            git add README.md
            git commit -m "Initial commit for dist branch"
            git push origin dist
          else
            git checkout dist
          fi

      - name: Ensure metrics folder exists
        run: mkdir -p metrics

      - name: Run Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          output_action: commit
          committer_branch: dist
          committer_message: "[Skip CI] Updating Metrics Picture"
          user: okisooo
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 12
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current

      - name: Favorites anime and currently watching
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.anilist.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: okiso
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1

      - name: Favorites characters
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics/metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: okiso
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22

      - name: Favorites mix (anime and characters)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.plugin.anilist.mix.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: okiso
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching, characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 22
