name: Metrics
on:
  # Schedule updates (Every 6 hours)
  schedule: [{ cron: "0 */6 * * *" }]
  # Allow manual triggering
  workflow_dispatch:
  # Run on every push (no branch filter)
  push: { branches: [] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token and commit settings
          token: ${{ secrets.ACCESS_TOKEN }}
          output_action: commit
          committer_branch: dist
          committer_message: "[Skip CI] Updating Metrics Picture"

          # Main options
          user: auravoid
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome

          # Achievements options
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 12
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          # WakaTime options
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current

      - name: Favorites anime and currently watching
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: okiso
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1

      - name: Favorites characters
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: okiso
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22

      - name: Favorites mix (anime and characters)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.mix.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: okiso
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching, characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 22
